-- ==============================================================
-- DBMS name:      PostgreSQL
-- Created on:     30/05/2024 15:22:22
-- ==============================================================

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_inconven_reference_producci') THEN
        ALTER TABLE INCONVENIENTE
            DROP CONSTRAINT FK_INCONVEN_REFERENCE_PRODUCCI;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_inventar_reference_ventas') THEN
        ALTER TABLE INVENTARIO_PRODUCTO_TERMINADO
            DROP CONSTRAINT FK_INVENTAR_REFERENCE_VENTAS;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_inventar_reference_producci') THEN
        ALTER TABLE INVENTARIO_PRODUCTO_TERMINADO
            DROP CONSTRAINT FK_INVENTAR_REFERENCE_PRODUCCI;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_producci_reference_inventar') THEN
        ALTER TABLE PRODUCCION
            DROP CONSTRAINT FK_PRODUCCI_REFERENCE_INVENTAR;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_producci_reference_producci') THEN
        ALTER TABLE PRODUCCION_ETAPA
            DROP CONSTRAINT FK_PRODUCCI_REFERENCE_PRODUCCI;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_producci_reference_etapa') THEN
        ALTER TABLE PRODUCCION_ETAPA
            DROP CONSTRAINT FK_PRODUCCI_REFERENCE_ETAPA;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_usuario_reference_rol') THEN
        ALTER TABLE USUARIO
            DROP CONSTRAINT FK_USUARIO_REFERENCE_ROL;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_usuario__reference_usuario') THEN
        ALTER TABLE USUARIO_MATERIA_PRIMA
            DROP CONSTRAINT FK_USUARIO__REFERENCE_USUARIO;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_usuario__reference_inventar') THEN
        ALTER TABLE USUARIO_MATERIA_PRIMA
            DROP CONSTRAINT FK_USUARIO__REFERENCE_INVENTAR;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_ventas_reference_usuario') THEN
        ALTER TABLE VENTAS
            DROP CONSTRAINT FK_VENTAS_REFERENCE_USUARIO;
    END IF;
END $$;

DROP TABLE IF EXISTS ETAPA CASCADE;
DROP TABLE IF EXISTS INCONVENIENTE CASCADE;
DROP TABLE IF EXISTS INVENTARIO_MATERIA_PRIMA CASCADE;
DROP TABLE IF EXISTS INVENTARIO_PRODUCTO_TERMINADO CASCADE;
DROP TABLE IF EXISTS PRODUCCION CASCADE;
DROP TABLE IF EXISTS PRODUCCION_ETAPA CASCADE;
DROP TABLE IF EXISTS ROL CASCADE;
DROP TABLE IF EXISTS USUARIO CASCADE;
DROP TABLE IF EXISTS USUARIO_MATERIA_PRIMA CASCADE;
DROP TABLE IF EXISTS VENTAS CASCADE;

-- ==============================================================
-- Table: ETAPA
-- ==============================================================
CREATE TABLE ETAPA 
(
   ID_ETAPA             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   ETAPA                TEXT                           NULL,
   DESCRIPCION          TEXT                           NULL
);

-- ==============================================================
-- Table: INCONVENIENTE
-- ==============================================================
CREATE TABLE INCONVENIENTE 
(
   ID_INCONVENIENTE     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   ID_PRODUCCION        INTEGER                        NULL,
   DESCRIPCION          TEXT                           NULL
);

-- ==============================================================
-- Table: INVENTARIO_MATERIA_PRIMA
-- ==============================================================
CREATE TABLE INVENTARIO_MATERIA_PRIMA 
(
   ID_MATERIA_PRIMA     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   NOMBRE               TEXT                           NULL,
   DESCRIPCION          TEXT                           NULL,
   PROVEEDOR            TEXT                           NULL,
   CANTIDAD_INGRESO     INTEGER                        NULL,
   CANTIDAD_DISPONIBLE  INTEGER                        NULL
);

-- ==============================================================
-- Table: INVENTARIO_PRODUCTO_TERMINADO
-- ==============================================================
CREATE TABLE INVENTARIO_PRODUCTO_TERMINADO 
(
   ID_PRODUCTO          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   ID_PRODUCCION        INTEGER                        NULL,
   CANTIDAD_DISPONIBLE  INTEGER                        NULL,
   NOMBRE               TEXT                           NULL
);

-- ==============================================================
-- Table: PRODUCCION
-- ==============================================================
CREATE TABLE PRODUCCION 
(
   ID_PRODUCCION        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   ID_MATERIA_PRIMA     INTEGER                        NULL,
   FECHA                DATE                           NULL,
   CANTIDAD_USO         INTEGER                        NULL,
   DESCRIPCION          TEXT                           NULL
);

-- ==============================================================
-- Table: PRODUCCION_ETAPA
-- ==============================================================
CREATE TABLE PRODUCCION_ETAPA 
(
   ID_PRODUCCION        INTEGER                        NOT NULL,
   ID_ETAPA             INTEGER                        NOT NULL,
   HORA_INICIO          TIME                           NULL,
   HORA_FIN             TIME                           NULL,
   ESTADO               TEXT                           NULL,
   CONSTRAINT PK_PRODUCCION_ETAPA PRIMARY KEY (ID_PRODUCCION, ID_ETAPA)
);

-- ==============================================================
-- Table: ROL
-- ==============================================================
CREATE TABLE ROL 
(
   ID_ROL               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   NOMBRE_ROL           TEXT                           NULL,
   DESCRIPCION          TEXT                           NULL
);

-- ==============================================================
-- Table: USUARIO
-- ==============================================================
CREATE TABLE USUARIO 
(
   ID_USUARIO           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   ID_ROL               INTEGER                        NULL,
   CEDULA               TEXT                           NULL,
   NOMBRE_USUARIO       TEXT                           NULL,
   APELLIDO_USUARIO     TEXT                           NULL,
   EMAIL                TEXT                           NULL,
   CONTRASENA           TEXT                           NULL,
   TELEFONO             NUMERIC                        NULL
);

-- ==============================================================
-- Table: USUARIO_MATERIA_PRIMA
-- ==============================================================
CREATE TABLE USUARIO_MATERIA_PRIMA 
(
   ID_USUARIO           INTEGER                        NOT NULL,
   ID_MATERIA_PRIMA     INTEGER                        NOT NULL,
   FECHA_INGRESO        DATE                           NULL,
   CANTIDAD_NUEVO_INGRESO INTEGER                      NULL,
   CONSTRAINT PK_USUARIO_MATERIA_PRIMA PRIMARY KEY (ID_USUARIO, ID_MATERIA_PRIMA)
);

-- ==============================================================
-- Table: VENTAS
-- ==============================================================
CREATE TABLE VENTAS 
(
   ID_VENTA             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   ID_USUARIO           INTEGER                        NULL,
   ID_PRODUCTO          INTEGER                        NULL,
   DESCRIPCION          TEXT                           NULL,
   CANTIDAD             INTEGER                        NULL
);

ALTER TABLE INCONVENIENTE
   ADD CONSTRAINT FK_INCONVEN_REFERENCE_PRODUCCI FOREIGN KEY (ID_PRODUCCION)
      REFERENCES PRODUCCION (ID_PRODUCCION)
      ON UPDATE RESTRICT
      ON DELETE CASCADE;

ALTER TABLE INVENTARIO_PRODUCTO_TERMINADO
   ADD CONSTRAINT FK_INVENTAR_REFERENCE_PRODUCCI FOREIGN KEY (ID_PRODUCCION)
      REFERENCES PRODUCCION (ID_PRODUCCION)
      ON UPDATE RESTRICT
      ON DELETE CASCADE;

ALTER TABLE PRODUCCION
   ADD CONSTRAINT FK_PRODUCCI_REFERENCE_INVENTAR FOREIGN KEY (ID_MATERIA_PRIMA)
      REFERENCES INVENTARIO_MATERIA_PRIMA (ID_MATERIA_PRIMA)
      ON UPDATE RESTRICT
      ON DELETE CASCADE;

ALTER TABLE PRODUCCION_ETAPA
   ADD CONSTRAINT FK_PRODUCCI_REFERENCE_PRODUCCI FOREIGN KEY (ID_PRODUCCION)
      REFERENCES PRODUCCION (ID_PRODUCCION)
      ON UPDATE RESTRICT
      ON DELETE CASCADE;

ALTER TABLE PRODUCCION_ETAPA
   ADD CONSTRAINT FK_PRODUCCI_REFERENCE_ETAPA FOREIGN KEY (ID_ETAPA)
      REFERENCES ETAPA (ID_ETAPA)
      ON UPDATE RESTRICT
      ON DELETE CASCADE;

ALTER TABLE USUARIO
   ADD CONSTRAINT FK_USUARIO_REFERENCE_ROL FOREIGN KEY (ID_ROL)
      REFERENCES ROL (ID_ROL)
      ON UPDATE RESTRICT
      ON DELETE CASCADE;

ALTER TABLE USUARIO_MATERIA_PRIMA
   ADD CONSTRAINT FK_USUARIO__REFERENCE_USUARIO FOREIGN KEY (ID_USUARIO)
      REFERENCES USUARIO (ID_USUARIO)
      ON UPDATE RESTRICT
      ON DELETE CASCADE;

ALTER TABLE USUARIO_MATERIA_PRIMA
   ADD CONSTRAINT FK_USUARIO__REFERENCE_INVENTAR FOREIGN KEY (ID_MATERIA_PRIMA)
      REFERENCES INVENTARIO_MATERIA_PRIMA (ID_MATERIA_PRIMA)
      ON UPDATE RESTRICT
      ON DELETE CASCADE;

ALTER TABLE VENTAS
   ADD CONSTRAINT FK_VENTAS_REFERENCE_USUARIO FOREIGN KEY (ID_USUARIO)
      REFERENCES USUARIO (ID_USUARIO)
      ON UPDATE RESTRICT
      ON DELETE CASCADE;

ALTER TABLE VENTAS
   ADD CONSTRAINT FK_VENTAS_REFERENCE_PRODUCTO FOREIGN KEY (ID_PRODUCTO)
      REFERENCES INVENTARIO_PRODUCTO_TERMINADO (ID_PRODUCTO)
      ON UPDATE RESTRICT
      ON DELETE CASCADE;

